import { CalendarDays, CalendarOff, CheckCircle, Clock, Loader2, Trash2, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import api from '../../lib/api';
import notify from '../../lib/toast';
import { formatDate, formatRelative } from '../../lib/utils';
import { Badge, Card, Modal, SectionHeader, StatCard } from '../../shared/components/UI';

const VARIANTS = { PENDING: 'warning', APPROVED: 'success', REJECTED: 'danger', CANCELLED: 'default' };
const Leave = () => {
  const [items, setItems] = useState([]); const [stats, setStats] = useState(null); const [filter, setFilter] = useState('PENDING'); const [selected, setSelected] = useState(null); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [list, summary] = await Promise.all([api.get('/leave', { params: { limit: 100, status: filter === 'ALL' ? undefined : filter } }), api.get('/leave/stats')]); setItems(list.data.items); setStats(summary.data); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [filter]);
  const review = async (status) => { try { await api.patch(`/leave/${selected.id}/review`, { status, reviewNote: note || undefined }); notify.success(`Leave ${status.toLowerCase()}.`); setSelected(null); load(); } catch (error) { notify.error(error.response?.data?.error || 'Review failed.'); } };
  const remove = async () => { try { await api.delete(`/leave/${selected.id}`); notify.success('Request deleted.'); setSelected(null); load(); } catch (error) { notify.error(error.response?.data?.error || 'Delete failed.'); } };
  if (loading && !stats) return <div className="flex items-center justify-center min-h-[60vh]"><Loader2 className="animate-spin" size={28} /></div>;
  return <div className="space-y-6"><SectionHeader title="Leave Management" subtitle="Organization-wide leave requests and approvals" />{stats && <div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><StatCard title="Pending" value={stats.pending} icon={Clock} color="#ff6d34" /><StatCard title="Approved" value={stats.approved} icon={CheckCircle} color="#00bea3" /><StatCard title="Rejected" value={stats.rejected} icon={XCircle} color="#dc2626" /><StatCard title="Days taken" value={stats.daysTaken} icon={CalendarDays} color="#7C3AED" /></div>}<div className="flex gap-2 flex-wrap">{['ALL', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'].map((value) => <button key={value} onClick={() => setFilter(value)} className={`px-4 py-1.5 rounded-full text-sm ${filter === value ? 'bg-purple-600 text-white' : 'border'}`}>{value}</button>)}</div><div className="space-y-3">{items.map((leave) => <Card key={leave.id} className="p-5 cursor-pointer" onClick={() => { setSelected(leave); setNote(leave.reviewNote || ''); }}><div className="flex items-center gap-4"><CalendarOff size={22} /><div className="flex-1"><h3 className="font-semibold">{leave.user?.name} · {leave.type} · {leave.days} day{leave.days > 1 ? 's' : ''}</h3><p className="text-xs text-slate-400">{leave.user?.department || '-'} · {formatDate(leave.startDate)} - {formatDate(leave.endDate)} · {formatRelative(leave.createdAt)}</p><p className="text-sm mt-1" style={{ color: 'var(--muted)' }}>{leave.reason}</p></div><Badge variant={VARIANTS[leave.status]}>{leave.status}</Badge></div></Card>)}{!items.length && <p className="text-center py-16 text-slate-400">No leave requests in this view.</p>}</div><Modal isOpen={!!selected} onClose={() => setSelected(null)} title="Review leave request" footer={<>{selected && <button onClick={remove} className="flex items-center gap-2 px-3 py-2 text-red-600"><Trash2 size={14} /> Delete</button>}{selected?.status === 'PENDING' && <><button onClick={() => review('REJECTED')} className="flex items-center gap-2 px-4 py-2 text-red-600 border rounded-lg"><XCircle size={14} /> Reject</button><button onClick={() => review('APPROVED')} className="flex items-center gap-2 px-4 py-2 text-white rounded-lg bg-purple-600"><CheckCircle size={14} /> Approve</button></>}</>}>{selected && <div className="space-y-3"><p className="font-semibold">{selected.user?.name}</p><p className="text-xs">{selected.type} leave · {formatDate(selected.startDate)} - {formatDate(selected.endDate)}</p><p>{selected.reason}</p>{selected.status === 'PENDING' && <textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} placeholder="Note (optional)" className="w-full border rounded-lg p-2" />}</div>}</Modal></div>;
};
export default Leave;